[package]
authors = ["tamasfe"]
categories = ["parser-implementations", "parsing"]
description = "A TOML parser, analyzer and formatter library"
edition = "2018"
homepage = "https://github.com/tamasfe/taplo"
keywords = ["toml", "parser", "formatter", "linter"]
license = "MIT"
name = "taplo"
readme = "../README.md"
repository = "https://github.com/tamasfe/taplo"
version = "0.1.0"

[features]
default = ["serde", "verify", "rewrite", "schema"]
schema = ["once_cell", "schemars", "serde_json"]
rewrite = []

[dependencies]
indexmap = "1.6.0"
logos = "0.11.4"
"lsp-types" = { version = "0.74.1" }
rowan = "0.10.0"
smallvec = "1.4"
regex = "1.4"
glob = "0.3"

chrono = { version = "0.4" }
# time = { version = "0.2", optional = true } TODO(time)

serde = { version = "1.0", optional = true }
verify = { version = "0.3", features = ["schemars"], optional = true }
once_cell = { version = "1.4", optional = true }
schemars = { version = "0.8", optional = true }
serde_json = { version = "*", optional = true }

[dev-dependencies]
assert-json-diff = "1.1"
serde_json = "1"
toml = "0.5"

[package.metadata.docs.rs]
all-features = true
