[package]
authors = ["tamasfe"]
categories = ["parser-implementations", "parsing"]
description = "A TOML parser, analyzer and formatter library"
edition = "2018"
homepage = "https://github.com/tamasfe/taplo"
keywords = ["toml", "parser", "formatter", "linter"]
license = "MIT"
name = "taplo"
readme = "../README.md"
repository = "https://github.com/tamasfe/taplo"
version = "1.0.0-alpha.1"

[features]
default = ["serde", "verify", "rewrite"]
rewrite = []

[dependencies]
chrono = "0.4.11"
indexmap = "1.6.0"
logos = "0.11.4"
lsp-types = { version = "0.74.1" }
rowan = "0.10.0"
serde = { version = "1.0", optional = true }
verify = { version = "0.3", features = ["schemars"], optional = true }
smallvec = "1.4"

# Don't use, only for schema generation
schemars = { version = "0.8.0-alpha-4", optional = true }

[dev-dependencies]
assert-json-diff = "1.1"
serde_json = "1"
toml = "0.5"

[package.metadata.docs.rs]
all-features = true
