[workspace]
members = ["crates/*"]
exclude = ["util/test-gen", "crates/taplo-wasm"]

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
strip = "debuginfo"

[profile.bench]
lto = true
opt-level = 3
