[workspace]
exclude = ["util/schema-gen", "util/test-gen"]
members = ["taplo-ide", "taplo-cli", "taplo", "lsp-async-stub"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[profile.bench]
lto = true
opt-level = 3

[patch.crates-io]
os_str_bytes = { path = "../os_str_bytes" }
