[package]
authors = ["tamasfe"]
edition = "2018"
name = "taplo-cli"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]


[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3"
pretty-lint = { version = "0.1.0" }
schemars = "0.8"
serde = "1"
serde_json = "1"
taplo = { version = "*", path = "../taplo", features = ["serde", "verify", "schemars"] }
toml = "0.5"
verify = { version = "0.3", features = ["schemars"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
once_cell = "1.4"

[[bin]]
name = "taplo"
path = "bin/taplo.rs"
