[package]
authors = ["tamasfe"]
edition = "2018"
name = "taplo-cli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3"
pretty-lint = { version = "0.1.0" }
schemars = "0.8.0-alpha-4"
serde = "1"
serde_json = "1"
taplo = { version = "*", path = "../taplo", features = ["serde", "verify", "schemars"] }
toml = "0.5"
verify = { version = "0.3", features = ["schemars"] }

[[bin]]
name = "taplo"
path = "bin/taplo.rs"