name: Releases

on:
  push:
    tags:
      - release-*

jobs:
  wait_for_ci:
    name: Wait for CI Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: "Continuous integration"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  cargo_publish_taplo:
    name: Cargo publish taplo
    runs-on: ubuntu-latest
    needs: ["wait_for_ci"]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/release-taplo-')
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Publish to Crates.io
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_wait_seconds: 60
          command: cd crates/taplo && cargo publish --allow-dirty --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  cargo_publish_taplo_cli:
    name: Cargo publish taplo-cli
    runs-on: ubuntu-latest
    needs: ["wait_for_ci"]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/release-taplo-cli-')
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Publish to Crates.io
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_wait_seconds: 60
          command: cd crates/taplo-cli && cargo publish --allow-dirty --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  cargo_publish_taplo_common:
    name: Cargo publish taplo-common
    runs-on: ubuntu-latest
    needs: ["wait_for_ci"]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/release-taplo-common-')
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Publish to Crates.io
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_wait_seconds: 60
          command: cd crates/taplo-common && cargo publish --allow-dirty --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  cargo_publish_taplo_lsp:
    name: Cargo publish taplo-lsp
    runs-on: ubuntu-latest
    needs: ["wait_for_ci"]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/release-taplo-lsp-')
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Publish to Crates.io
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_wait_seconds: 60
          command: cd crates/taplo-lsp && cargo publish --allow-dirty --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  cargo_publish_lsp_async_stub:
    name: Cargo publish taplo-common
    runs-on: ubuntu-latest
    needs: ["wait_for_ci"]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/release-lsp-async-stub-')
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Publish to Crates.io
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_wait_seconds: 60
          command: cd crates/lsp-async-stub && cargo publish --allow-dirty --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
  
  cli_binaries:
    name: Publish and release Taplo CLI binaries
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/release-cli-')
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          # - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            base: taplo
            name: x86_64-unknown-linux-gnu.tar.gz
          # - target: x86_64-pc-windows-gnu
          #   os: ubuntu-latest
          #   base: taplo.exe
          #   name: x86_64-pc-windows-gnu.zip
          - target: x86_64-apple-darwin
            os: macos-latest
            base: taplo
            name: x86_64-apple-darwin-gnu.tar.gz
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Retrieve release version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/tags/release-cli-})" >> $GITHUB_ENV

      - name: Install dependencies
        if: ${{ matrix.target == 'x86_64-pc-windows-gnu' }}
        run: |
          sudo apt update && sudo apt install mingw-w64

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build full binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin taplo --features "toml-test lsp" --target=${{ matrix.target }}

      - name: Rename full binary
        run: |
          mv target/${{ matrix.target }}/release/taplo target/${{ matrix.target }}/release/taplo-full

      - name: Build default binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin taplo --target=${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]
          then
            zip "../../../taplo-$RELEASE_VERSION-${{ matrix.name }}" ${{ matrix.base }}
          else
            tar czvf "../../../taplo-$RELEASE_VERSION-${{ matrix.name }}" ${{ matrix.base }}
            rm taplo
            mv taplo-full taplo
            tar czvf "../../../taplo-full-$RELEASE_VERSION-${{ matrix.name }}" ${{ matrix.base }}
          fi
          cd -

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Taplo CLI ${{ env.RELEASE_VERSION }}
          # Only for merging three releases
          draft: true
          prerelease: false
          files: |
            taplo-*.tar.gz
            taplo-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
